# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='pub_name',
            new_name='pubname',
        ),
    ]
