# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0002_auto_20170624_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(max_length=20, null=True),
        ),
    ]
